Feature/approval
starkbank/sdk-java pull request #30
Opened 2020-09-22 19:05 UTC by LucasStarkBank

2020-09-27 16:41 UTC, cdottori-stark requested changes

2020-09-27 16:41 UTC, cdottori-stark commented on src/main/java/com/starkbank/PaymentRequest.java
> +     *     <item>Created [String]: creation datetime for the PaymentRequest. ex: 2020-12-31</item>
Parece que as docstrings estão seguindo o padrão do SDK C# (CenterID) em vez do Java (centerId)

2020-09-27 16:41 UTC, cdottori-stark commented on src/main/java/com/starkbank/PaymentRequest.java
> +     *     <item>Actions [list of maps]: list of actions that are affecting this PaymentRequest.ex: [{"type": "member", "id": "56565656565656, "action": "requested"}]</item>
Acho que vale confirmar se vamos mesmo colocar o actions nos SDKs, talvez seja melhor não mapear. Na próxima reunião fechamos esse ponto.

2020-09-27 16:41 UTC, cdottori-stark commented on src/main/java/com/starkbank/PaymentRequest.java
> +     *       *     centerId [String]: target cost-center ID. ex: "5656565656565656"
Espaço a mais aqui

2020-09-27 16:41 UTC, cdottori-stark commented on src/main/java/com/starkbank/utils/PaymentRequestDeserializer.java
> +                throw new JsonParseException("Invalid resource type.");
Acho melhor deixar como hashmap em vez de dar erro se não for reconhecido pra não quebrar o SDK de alguém que esteja numa versão antiga depois que lançarmos um tipo de pagamento novo.

2020-09-27 16:41 UTC, cdottori-stark commented on src/test/java/TestPaymentRequest.java
> +        return new PaymentRequest(null, "5706232262295552", payment, null, due, null, null, null, null, null, null);
Melhor seguir aquele padrão que falamos de colocar o center ID numa variável de ambiente pra facilitar os testes

2020-10-16 21:58 UTC, cdottori-stark approved these changes

2020-10-19 21:16 UTC, vidalstark approved these changes

2020-10-19 21:16 UTC, vidalstark commented on src/main/java/com/starkbank/PaymentRequest.java
> +        this.amount = (Long)((Number) dataCopy.remove("amount"));
Só adicionei um cast pra long aqui, porque tava dando pau com o método .LongValue quando amount não era passado.

2020-10-19 21:16 UTC, vidalstark commented on src/main/java/com/starkbank/PaymentRequest.java
> +        this.amount = (Long)((Number) dataCopy.remove("amount"));
Dava isso aqui:
 Exception in thread "main" java.lang.NullPointerException
	at gfg.main(gfg.java:11)

2020-10-19 22:52 UTC, merged